"""Report generation in Markdown, PDF, and JSON formats."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from fpdf import FPDF


@dataclass
class SourceInfo:
    """Source metadata for report."""

    url: str
    title: str
    credibility_score: float
    credibility_rating: str
    word_count: int
    snippet: str = ""


@dataclass
class ReportData:
    """All data needed to generate a report."""

    query: str
    summary: str
    key_sentences: list[str]
    entities: dict[str, list[str]]
    key_phrases: list[str]
    statistics: list[str]
    claims: list[str]
    sources: list[SourceInfo]
    consensus_points: list[str]
    conflict_points: list[str]
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    )


@dataclass
class ReportGenerator:
    """Generate research reports in multiple formats."""

    output_dir: Path = Path.home() / ".researchbot" / "reports"

    def __post_init__(self) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _safe_filename(self, query: str) -> str:
        safe = "".join(c if c.isalnum() or c in " -_" else "" for c in query)
        return safe[:60].strip().replace(" ", "_")

    def generate_markdown(self, data: ReportData) -> str:
        """Generate a Markdown report string."""
        lines: list[str] = []
        lines.append(f"# Research Report: {data.query}\n")
        lines.append(f"*Generated: {data.timestamp}*\n")
        lines.append(f"*Sources analyzed: {len(data.sources)}*\n")

        # Summary
        lines.append("## Summary\n")
        lines.append(f"{data.summary}\n")

        # Key findings
        if data.key_sentences:
            lines.append("## Key Findings\n")
            for s in data.key_sentences:
                lines.append(f"- {s}")
            lines.append("")

        # Entities
        if data.entities:
            lines.append("## Named Entities\n")
            for label, ents in data.entities.items():
                lines.append(f"**{label}:** {', '.join(ents[:10])}\n")

        # Key phrases
        if data.key_phrases:
            lines.append("## Key Topics\n")
            for phrase in data.key_phrases[:15]:
                lines.append(f"- {phrase}")
            lines.append("")

        # Statistics
        if data.statistics:
            lines.append("## Statistics & Data Points\n")
            for stat in data.statistics:
                lines.append(f"- {stat}")
            lines.append("")

        # Claims
        if data.claims:
            lines.append("## Notable Claims\n")
            for claim in data.claims:
                lines.append(f"> {claim}\n")

        # Consensus / Conflicts
        if data.consensus_points:
            lines.append("## Source Consensus\n")
            lines.append("Points where multiple sources agree:\n")
            for point in data.consensus_points:
                lines.append(f"- {point}")
            lines.append("")

        if data.conflict_points:
            lines.append("## Conflicting Information\n")
            lines.append("Points where sources disagree:\n")
            for point in data.conflict_points:
                lines.append(f"- {point}")
            lines.append("")

        # Sources
        lines.append("## Sources\n")
        lines.append("| # | Title | Credibility | Words |")
        lines.append("|---|-------|-------------|-------|")
        for i, src in enumerate(data.sources, 1):
            title_link = f"[{src.title[:50]}]({src.url})" if src.title else src.url
            lines.append(
                f"| {i} | {title_link} | {src.credibility_rating} ({src.credibility_score:.0%}) | {src.word_count} |"
            )
        lines.append("")

        lines.append("---\n")
        lines.append("*Generated by [ResearchBot](https://github.com/akash/researchbot) -- AI Web Research Agent*")

        return "\n".join(lines)

    def save_markdown(self, data: ReportData) -> Path:
        """Save Markdown report to file."""
        content = self.generate_markdown(data)
        filename = f"{self._safe_filename(data.query)}.md"
        path = self.output_dir / filename
        path.write_text(content, encoding="utf-8")
        return path

    def save_pdf(self, data: ReportData) -> Path:
        """Save PDF report."""
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, f"Research Report: {data.query}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 6, f"Generated: {data.timestamp} | Sources: {len(data.sources)}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Summary
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        # Encode to latin-1 safe text for fpdf
        safe_summary = data.summary.encode("latin-1", "replace").decode("latin-1")
        pdf.multi_cell(0, 5, safe_summary)
        pdf.ln(4)

        # Key Findings
        if data.key_sentences:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, "Key Findings", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            for s in data.key_sentences[:10]:
                safe = s.encode("latin-1", "replace").decode("latin-1")
                pdf.multi_cell(0, 5, f"  * {safe}")
                pdf.ln(1)
            pdf.ln(3)

        # Statistics
        if data.statistics:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, "Statistics & Data Points", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            for stat in data.statistics[:10]:
                safe = stat.encode("latin-1", "replace").decode("latin-1")
                pdf.multi_cell(0, 5, f"  * {safe}")
                pdf.ln(1)
            pdf.ln(3)

        # Sources table
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Sources", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for i, src in enumerate(data.sources, 1):
            title = (src.title or src.url)[:60].encode("latin-1", "replace").decode("latin-1")
            pdf.cell(0, 5, f"{i}. {title} [{src.credibility_rating}]", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "I", 8)
            url_safe = src.url[:80].encode("latin-1", "replace").decode("latin-1")
            pdf.cell(0, 4, f"   {url_safe}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)

        filename = f"{self._safe_filename(data.query)}.pdf"
        path = self.output_dir / filename
        pdf.output(str(path))
        return path

    def save_json(self, data: ReportData) -> Path:
        """Save JSON report."""
        output: dict[str, Any] = {
            "query": data.query,
            "timestamp": data.timestamp,
            "summary": data.summary,
            "key_sentences": data.key_sentences,
            "entities": data.entities,
            "key_phrases": data.key_phrases,
            "statistics": data.statistics,
            "claims": data.claims,
            "consensus_points": data.consensus_points,
            "conflict_points": data.conflict_points,
            "sources": [
                {
                    "url": s.url,
                    "title": s.title,
                    "credibility_score": s.credibility_score,
                    "credibility_rating": s.credibility_rating,
                    "word_count": s.word_count,
                }
                for s in data.sources
            ],
        }
        filename = f"{self._safe_filename(data.query)}.json"
        path = self.output_dir / filename
        path.write_text(json.dumps(output, indent=2, ensure_ascii=False), encoding="utf-8")
        return path
